title: Chris DeGarmo # your name (or website title) here
logo: "images/headshot.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Throughout my career, I've applied cutting-edge geospatial technologies to real-world challenges, from detecting wildfires with PyTorch-based models and mapping Hurricane Helene's impacts through InSAR coherence analysis, to developing continental-scale land cover pipelines using Sentinel-2 super-resolution techniques. My work spans SAR/InSAR processing, optical imagery analysis, machine learning model development, and custom ArcGIS Pro tooling, with hands-on experience using platforms like SNAP, Google Earth Engine, and PyTorch to deliver actionable insights from complex spatial data.
  
  <br><br>
  <a href="https://www.linkedin.com/in/christopher-degarmo-856ba758/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-MVCNJ94SFY # your Google Analytics tracking ID here
