title: Chris DeGarmo # your name (or website title) here
logo: "images/headshot.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Geospatial technologist specializing in SAR/InSAR processing, machine learning, and optical imagery analysis.
  <br><br>
  <a href="https://www.linkedin.com/in/christopher-degarmo-m-s-856ba758/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-MVCNJ94SFY # your Google Analytics tracking ID here
